### ISSUE TITLE
As a customer I would like to see the details of an order

### ISSUE THREAD

**Issue by miguel57403** [miguel57403/safe-eat-android#24]
Deve criar a tela de detalhes do pedido conforme o mockup (veja as três imagens abaixo)

![Image](https://user-images.githubusercontent.com/128187386/236876709-e8e7c3a8-07e0-44df-852c-79d3e3ae0a88.png)
![Image](https://user-images.githubusercontent.com/128187386/236876708-db4250d0-5494-4776-ab24-3cca2dde610d.png)
![Image](https://user-images.githubusercontent.com/128187386/236876710-d114b65d-164a-4c07-907b-10c1aa4c5810.png)

**Comment by daniel57060** [comment]
Branch "issue-24"
